##### 问题
你需要执行矩阵和线性代数运算，比如矩阵乘法、寻找行列式、求解线性方程组等等。
##### 解决方案
numpy库中一个矩阵对象可以用来解决这个问题。
下面的一个例子展示了矩阵的一些基本特性：

In [2]:
import numpy as np 

m = np.matrix([[1, -2, 3], [0, 4, 5], [7, 8, -9]])
m

matrix([[ 1, -2,  3],
        [ 0,  4,  5],
        [ 7,  8, -9]])

In [3]:
m.T

matrix([[ 1,  0,  7],
        [-2,  4,  8],
        [ 3,  5, -9]])

In [4]:
m.I

matrix([[ 0.33043478, -0.02608696,  0.09565217],
        [-0.15217391,  0.13043478,  0.02173913],
        [ 0.12173913,  0.09565217, -0.0173913 ]])

In [5]:
v = np.matrix([[2], [3], [4]])
v

matrix([[2],
        [3],
        [4]])

In [6]:
m * v

matrix([[ 8],
        [32],
        [ 2]])

可以在`numpy.linalg`子包中找到更多的操作函数，比如：

In [7]:
np.linalg.det(m) # 计算矩阵的行列式

-229.99999999999983

In [8]:
np.linalg.eigvals(m) # 求矩阵的特征值

array([-13.11474312,   2.75956154,   6.35518158])

In [9]:
x = np.linalg.solve(m, v) # 求解线性方程或线性标量方程组
x

matrix([[0.96521739],
        [0.17391304],
        [0.46086957]])

In [10]:
m * x

matrix([[2.],
        [3.],
        [4.]])

In [11]:
v

matrix([[2],
        [3],
        [4]])

##### 讨论
很显然线性代数是个非常大的主题，已经超出了本书能讨论的范围，而NumPy是一个不错的入口点。