##### 问题
你需要在大数据集（比如数组或矩阵）上面执行计算。
##### 解决方案
涉及到数组的重量级运算操作，可以使用NumPy库。NumPy的一个主要特征是它会给python提供一个数组对象，相比标准的python列表而已更合适用来做数学运算。下面试一个简单的小例子，展示标准列表对象和NumPy数组对象之间的差别：

In [2]:
x = [1, 2, 3, 4]
y = [5, 6, 7, 8]
x * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [3]:
x + 10

TypeError: can only concatenate list (not "int") to list

In [4]:
x + y

[1, 2, 3, 4, 5, 6, 7, 8]

In [5]:
import numpy as np
ax = np.array([1, 2, 3, 4])
ay = np.array([5, 6, 7, 8])
ax * 2

array([2, 4, 6, 8])

In [6]:
ax + 10

array([11, 12, 13, 14])

In [7]:
ax + ay

array([ 6,  8, 10, 12])

In [8]:
ax * ay

array([ 5, 12, 21, 32])

正如所见，两种方案中数组是基本数学运算结果并不相同。特别的，numpy中是标量运算会作用在每一个元素上。另外，当两个操作数都是数组的时候执行元素对等位置计算，并最终生成一个新的数组。  
对整个数组中所有元素同时执行数学运算可以使得作用在整个数组上的函数运算简单而又快速。比如，如果你想计算多项式的值，可以这样做：

In [9]:
def f(x):
    return 3*x**2 - 2*x + 7

f(ax)

array([ 8, 15, 28, 47])

numpy 还为数组操作提供了大量的通用函数，这些函数可以作为math模块中类似函数的代替。

In [11]:
np.sqrt(ax)

array([1.        , 1.41421356, 1.73205081, 2.        ])

In [12]:
np.cos(ax)

array([ 0.54030231, -0.41614684, -0.9899925 , -0.65364362])

使用这些通用函数要比循环数组并使用math模块中的函数执行计算要快的多。因此，只要有可能的话尽可能选择numpy的数组方案。  
底层实现中，nunpy数组使用了C或者Fortan语言的机制分配内存。也就是说，它们是一个非常大的连续的并由同类数据组成的内存区域。所以，你可以构造一个比普通python列表大的多的数组。比如，你想构造一个10000*10000的浮点数二维网络，很轻松：

In [13]:
grid = np.zeros(shape=(10000, 10000), dtype=float)
grid

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]])

所有的普通操作还是会同时作用在所有元素上：

In [14]:
grid += 10
grid

array([[10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       ...,
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.],
       [10., 10., 10., ..., 10., 10., 10.]])

In [15]:
np.sin(grid)

array([[-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       ...,
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111],
       [-0.54402111, -0.54402111, -0.54402111, ..., -0.54402111,
        -0.54402111, -0.54402111]])

关于numpy有一点需要特别的注意，那就是它扩展python列表的索引功能，特别对于多维数组。为了说明清楚，先构造一个简单的二维数组并试着做些试验：

In [18]:
a = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
a

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [19]:
a[1]

array([5, 6, 7, 8])

In [20]:
a[:,1]

array([ 2,  6, 10])

In [21]:
a[1:3, 1:3]

array([[ 6,  7],
       [10, 11]])

In [22]:
a[1:3, 1:3] += 10
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [23]:
a + [100, 101, 102, 103]

array([[101, 103, 105, 107],
       [105, 117, 119, 111],
       [109, 121, 123, 115]])

In [24]:
a

array([[ 1,  2,  3,  4],
       [ 5, 16, 17,  8],
       [ 9, 20, 21, 12]])

In [25]:
np.where(a < 10, a, 10)

array([[ 1,  2,  3,  4],
       [ 5, 10, 10,  8],
       [ 9, 10, 10, 10]])

##### 讨论
numpy是python领域中很多科学与工程库的基础，同时也是被广泛使用的最大最复杂的模块。几遍如此，在刚开始的时候通过一些简单的例子和玩具程序也能帮我们完成一些有趣的事情。  
通常我们导入numpy模块的时候使用语句`import numpy as np`。这样的话你就不用在你的程序里面一遍遍的敲入numpy，只需要输入np就行，节省不少时间。